import type { CommandDefinition } from "./types";

/** All poker network commands — wired to live backend actions. */
export const COMMAND_REGISTRY: CommandDefinition[] = [
  // Platform
  {
    id: "healthz",
    capability: "guest",
    title: "Check Backend Health",
    description: "Verify the game server is online and responding.",
    category: "platform",
    status: "live",
    rpc: "healthz",
    icon: "◉",
  },
  {
    id: "stack_health",
    capability: "guest",
    title: "Live Stack Health",
    description: "Check every core service is healthy in one request.",
    category: "platform",
    status: "live",
    href: "/stack",
    icon: "⬡",
  },
  {
    id: "auth_sign_in",
    capability: "guest",
    title: "Sign In / Create Account",
    description: "Sign in or create your account (automatic on your first visit).",
    category: "platform",
    status: "live",
    rpc: "profile_get",
    href: "/login",
    icon: "◎",
    example: {},
  },
  {
    id: "auth_profile",
    title: "View Player Profile",
    description: "Load account metadata, username, and global wallet balance.",
    category: "platform",
    status: "live",
    rpc: "profile_get",
    icon: "◌",
  },
  {
    id: "wallet_get",
    title: "View Global Wallet",
    description: "Fetch your platform wallet balance (default $1,000 starting chips).",
    category: "platform",
    status: "live",
    rpc: "wallet_get",
    icon: "💵",
  },
  {
    id: "loyalty",
    title: "Loyalty & HRP",
    description: "High Roller Points, loyalty level, and achievements — earned by playing.",
    category: "platform",
    status: "live",
    rpc: "loyalty_get",
    href: "/loyalty",
    icon: "🏅",
  },
  {
    id: "kyc",
    capability: "guest",
    title: "Identity Verification",
    description: "Progressive KYC (Didit) — verify to unlock real-money deposits and higher limits.",
    category: "platform",
    status: "live",
    rpc: "kyc_status",
    href: "/kyc",
    icon: "🪪",
  },

  // Community & Clubs
  {
    id: "club_create",
    title: "Create Community",
    description: "Create a private club with you as its owner.",
    category: "community",
    status: "live",
    rpc: "club_create",
    icon: "♣",
    example: {
      name: "Midnight Hold'em Society",
      slug: "midnight-holdem",
      description: "Invite-only high stakes club",
      currency: "USD",
    },
  },
  {
    id: "club_list",
    title: "Browse Communities",
    description: "List all active clubs on the network.",
    category: "community",
    status: "live",
    rpc: "club_list",
    icon: "♣",
    example: {},
  },
  {
    id: "club_owner_add",
    title: "Add Club Owner",
    description: "Grant owner, manager, or agent role with equity split.",
    category: "community",
    status: "live",
    rpc: "club_owner_add",
    icon: "♦",
    requires: "club_admin",
    example: { club_id: "club_123", user_id: "user-id", role: "manager", equity_bps: 2500 },
  },
  {
    id: "balance_allocate",
    title: "Allocate Player Balance",
    description: "Credit chips to a player inside a club ledger.",
    category: "community",
    status: "live",
    rpc: "balance_allocate",
    icon: "♠",
    requires: "club_admin",
    example: { club_id: "club_123", user_id: "user-id", balance: 100000, currency: "USD" },
  },
  {
    id: "balance_get",
    title: "Get Club Balance",
    description: "Read a player's allocated balance inside a club.",
    category: "community",
    status: "live",
    rpc: "balance_get",
    icon: "♠",
    example: { club_id: "club_123", user_id: "user-id" },
  },
  {
    id: "rake_config_set",
    title: "Configure Rake Rules",
    description: "Set percent rake, cap, and no-flop-no-drop policy for a club.",
    category: "community",
    status: "live",
    rpc: "rake_config_set",
    icon: "♥",
    requires: "club_admin",
    example: { club_id: "club_123", name: "Standard", percent_bps: 500, cap_minor: 500 },
  },
  {
    id: "rake_config_get",
    title: "Get Rake Rules",
    description: "Read the active rake configuration for a club.",
    category: "community",
    status: "live",
    rpc: "rake_config_get",
    icon: "♥",
    example: { club_id: "club_123" },
  },

  // Cash Games
  {
    id: "game_create",
    capability: "guest",
    title: "Create Cash Game",
    description: "Open a cash table — set the seat count, blinds, buy-in, and how many players are needed to start.",
    category: "game",
    status: "live",
    rpc: "table_create",
    href: "/lobby",
    icon: "▶",
    example: { name: "Hold'em Table", small_blind: 100, big_blind: 200, buy_in: 100000 },
  },
  {
    id: "game_join",
    capability: "guest",
    title: "Join Cash Game",
    description: "Take a seat at an open cash game table.",
    category: "game",
    status: "live",
    href: "/lobby",
    icon: "▷",
  },
  {
    id: "game_list",
    capability: "guest",
    title: "List Open Tables",
    description: "Browse active cash game matches on the network.",
    category: "game",
    status: "live",
    rpc: "table_list",
    href: "/lobby",
    icon: "☰",
    example: {},
  },
  {
    id: "matchmaker_enqueue",
    capability: "guest",
    title: "Find Match (Matchmaker)",
    description: "Get matchmaker params, then join via socket on the table page.",
    category: "game",
    status: "live",
    rpc: "matchmaker_enqueue",
    href: "/lobby",
    icon: "⚡",
    example: { min_players: 2, max_players: 6, buy_in_cents: 100000 },
  },
  {
    id: "hand_rank",
    title: "Hand Rank",
    description: "Evaluate a hand's category and strength.",
    category: "game",
    status: "live",
    rpc: "hand_rank",
    href: "/table",
    icon: "♠",
    example: { cards: "AsKsQsJs2c" },
  },
  {
    id: "equity_estimate",
    title: "Equity Calculator",
    description: "Estimate pot equity between two or more known hands.",
    category: "game",
    status: "live",
    rpc: "equity_estimate",
    href: "/table",
    icon: "📊",
    example: { holes: ["AsAh", "7c2d"], board: "AdKhQh", iterations: 2000 },
  },
  {
    id: "game_leave",
    title: "Leave Table",
    description: "Stand up and cash out from the current game (use Stand Up on table).",
    category: "game",
    status: "live",
    href: "/table",
    icon: "◁",
  },

  // Tournaments
  {
    id: "tournament_create",
    title: "Create Tournament",
    description: "Schedule a multi-table tournament with buy-in, fee, and starting stack.",
    category: "tournament",
    status: "live",
    rpc: "tournament_create",
    href: "/tournaments",
    icon: "🏆",
    example: {
      name: "Friday Night 100",
      variant: "texas-holdem",
      buy_in_minor: 10000,
      fee_minor: 1000,
      starting_stack: 10000,
      max_players: 180,
      max_seats_per_table: 6,
    },
  },
  {
    id: "tournament_list",
    title: "Browse Tournaments",
    description: "View registering, running, and finished MTT events.",
    category: "tournament",
    status: "live",
    rpc: "tournament_list",
    href: "/tournaments",
    icon: "☰",
    example: {},
  },
  {
    id: "tournament_register",
    title: "Register for Tournament",
    description: "Buy in from your global wallet and reserve a seat.",
    category: "tournament",
    status: "live",
    rpc: "tournament_register",
    href: "/tournaments",
    icon: "✚",
    example: { tournament_id: "mtt_123" },
  },
  {
    id: "tournament_blinds",
    title: "Add Blind Level",
    description: "Add a blind level to a tournament structure.",
    category: "tournament",
    status: "live",
    rpc: "blind_level_add",
    icon: "⏱",
    example: { tournament_id: "mtt_123", level: 1, small_blind: 50, big_blind: 100, duration_secs: 600 },
  },
  {
    id: "tournament_blinds_list",
    title: "View Blind Structure",
    description: "Inspect blind levels, antes, and break schedule.",
    category: "tournament",
    status: "live",
    rpc: "blind_level_list",
    icon: "⏱",
    example: { tournament_id: "mtt_123" },
  },
  {
    id: "tournament_prizes",
    title: "Add Prize Tier",
    description: "Define payout tiers for tournament prize pool.",
    category: "tournament",
    status: "live",
    rpc: "prize_pool_add",
    icon: "💰",
    example: { tournament_id: "mtt_123", rank_from: 1, rank_to: 1, payout_bps: 5000 },
  },
  {
    id: "tournament_prizes_list",
    title: "View Prize Pool",
    description: "See payout tiers and guaranteed prize distribution.",
    category: "tournament",
    status: "live",
    rpc: "prize_pool_list",
    icon: "💰",
    example: { tournament_id: "mtt_123" },
  },
  {
    id: "tournament_start",
    title: "Start Tournament (Live MTT)",
    description: "Launch director match, table matches, blind clock, and balancing.",
    category: "tournament",
    status: "live",
    rpc: "tournament_start",
    href: "/tournaments",
    icon: "▶",
    example: { tournament_id: "mtt_123" },
  },
  {
    id: "rake_ledger_get",
    title: "View Rake Ledger",
    description: "House balance and rake collection history for a club.",
    category: "community",
    status: "live",
    rpc: "rake_ledger_get",
    icon: "📒",
    example: { club_id: "club_123" },
  },
  {
    id: "balancing_rule_set",
    title: "Set Table Balancing Rule",
    description: "Configure multi-table balancing strategy for a tournament.",
    category: "tournament",
    status: "live",
    rpc: "balancing_rule_set",
    icon: "⚖",
    example: { tournament_id: "mtt_123", max_seat_difference: 1, break_table_at_or_below: 2, strategy: "balanced" },
  },

  {
    id: "gto_advise",
    title: "GTO Action Advice",
    description: "Get a fold / call / bet recommendation from equity analysis.",
    category: "math",
    status: "live",
    rpc: "gto_advise",
    icon: "◎",
    example: {
      hero_hole: "AsKh",
      villain_holes: ["7c2d"],
      board: "QhJh2c",
      pot: 400,
      to_call: 200,
      iterations: 2000,
    },
  },
  {
    id: "omaha_rank",
    title: "Rank Omaha Hand",
    description: "Evaluate Omaha (PLO4–PLO7) hands.",
    category: "math",
    status: "live",
    rpc: "omaha_rank",
    icon: "♦",
    example: { hole: "AhAsKhKs", board: "QhJhTh" },
  },
  {
    id: "omaha_showdown",
    title: "Omaha Showdown",
    description: "Resolve Omaha winner indices between multiple hands.",
    category: "math",
    status: "live",
    rpc: "omaha_showdown",
    icon: "♦",
    example: { holes: ["AhAsKhKs", "QcQdJcJd"], board: "Th9h8h2c3d" },
  },
  {
    id: "coaching_tip",
    title: "Smart HUD Coaching Tip",
    description: "MCP-ready mistake alerts from equity vs pot odds analysis.",
    category: "coaching",
    status: "live",
    rpc: "coaching_tip",
    icon: "💡",
    example: {
      hero_hole: "AsKh",
      villain_holes: ["7c2d"],
      board: "QhJh2c",
      pot: 400,
      to_call: 200,
      last_action: "raise",
    },
  },
  {
    id: "antibot_score",
    title: "Anti-Bot Pattern Score",
    description: "ML bot-likelihood scoring runs automatically on every table; review flagged players here.",
    category: "security",
    status: "live",
    rpc: "antibot_score",
    icon: "🛡",
    requires: "platform_admin",
    example: {
      user_id: "player_1",
      actions: [
        { user_id: "player_1", action: "raise", amount: 200, pot_ratio: 0.5, street: "preflop" },
        { user_id: "player_1", action: "bet", amount: 300, pot_ratio: 0.5, street: "flop" },
      ],
    },
  },
  {
    id: "hand_history",
    title: "Hand History",
    description: "Browse your recent hands and verify the shuffle and payout of each — no IDs to paste.",
    category: "audit",
    status: "live",
    href: "/hands",
    icon: "⛓",
  },
  {
    id: "audit_verify_hand",
    title: "Verify Hand Integrity",
    description: "Open a hand from your history to check its hash chain and deck commitment.",
    category: "audit",
    status: "live",
    href: "/hands",
    icon: "✓",
  },

  // Table canvas
  {
    id: "table_open",
    title: "Open Table Canvas",
    description: "Open the cinematic 3D poker table.",
    category: "table",
    status: "live",
    href: "/table",
    icon: "▣",
  },
  {
    id: "table_deal",
    title: "Start Hand / Deal Cards",
    description: "Start a multiplayer hand — server deals hole cards to seated players.",
    category: "table",
    status: "live",
    href: "/table",
    icon: "🃏",
  },
];

export function commandsByCategory(category: CommandDefinition["category"]): CommandDefinition[] {
  return COMMAND_REGISTRY.filter((cmd) => cmd.category === category);
}

export function getCommand(id: string): CommandDefinition | undefined {
  return COMMAND_REGISTRY.find((cmd) => cmd.id === id);
}
