[build]
builder = "RAILPACK"
buildCommand = "npm ci && npm run build"
watchPatterns = ["frontend-table/**"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
