// Command schemagen reflects the annotated Go request structs into a JSON Schema
// bundle the frontend imports, so the Command Center renders real forms instead
// of raw JSON textareas (UI review P0-1). Run it whenever a form struct changes:
//
//	cd backend-core && go run ./cmd/schemagen
//
// It writes <out>/<rpc>.schema.json for every registered form RPC, an index.json
// manifest, and an index.ts barrel the frontend imports as a typed map.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/smithdouglas404/poker-next-gen/backend-core/apischema"
)

func main() {
	out := flag.String("out", "../frontend-table/src/features/commands/schemas", "output directory for the schema bundle")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "schemagen:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	schemas := apischema.Build()
	rpcs := make([]string, 0, len(schemas))
	for rpc := range schemas {
		rpcs = append(rpcs, rpc)
	}
	sort.Strings(rpcs)

	// One schema file per RPC.
	for _, rpc := range rpcs {
		b, err := json.MarshalIndent(schemas[rpc], "", "  ")
		if err != nil {
			return fmt.Errorf("marshal %s: %w", rpc, err)
		}
		b = append(b, '\n')
		if err := os.WriteFile(filepath.Join(outDir, rpc+".schema.json"), b, 0o644); err != nil {
			return err
		}
	}

	// Manifest.
	manifest, _ := json.MarshalIndent(map[string]interface{}{
		"generated_by": "backend-core/cmd/schemagen",
		"rpcs":         rpcs,
	}, "", "  ")
	manifest = append(manifest, '\n')
	if err := os.WriteFile(filepath.Join(outDir, "index.json"), manifest, 0o644); err != nil {
		return err
	}

	// TypeScript barrel: a typed RPC -> schema map the form renderer consumes.
	if err := os.WriteFile(filepath.Join(outDir, "index.ts"), []byte(barrel(rpcs)), 0o644); err != nil {
		return err
	}

	fmt.Printf("schemagen: wrote %d RPC schemas + index to %s\n", len(rpcs), outDir)
	return nil
}

func barrel(rpcs []string) string {
	var b strings.Builder
	b.WriteString("// GENERATED by backend-core/cmd/schemagen — DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the annotated Go request structs in backend-core.\n")
	b.WriteString("// Regenerate: cd backend-core && go run ./cmd/schemagen\n\n")
	b.WriteString("import type { RpcSchema } from \"../schemaForm/schemaTypes\";\n\n")
	for _, rpc := range rpcs {
		b.WriteString(fmt.Sprintf("import %s from \"./%s.schema.json\";\n", ident(rpc), rpc))
	}
	b.WriteString("\nexport const RPC_SCHEMAS: Record<string, RpcSchema> = {\n")
	for _, rpc := range rpcs {
		b.WriteString(fmt.Sprintf("  %q: %s as unknown as RpcSchema,\n", rpc, ident(rpc)))
	}
	b.WriteString("};\n\n")
	b.WriteString("export function getRpcSchema(rpc: string): RpcSchema | undefined {\n")
	b.WriteString("  return RPC_SCHEMAS[rpc];\n")
	b.WriteString("}\n")
	return b.String()
}

// ident turns an rpc id into a JS-safe identifier for the import binding.
func ident(rpc string) string {
	parts := strings.Split(rpc, "_")
	for i, p := range parts {
		if i == 0 || p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "") + "Schema"
}
