// GENERATED by backend-core/cmd/schemagen — DO NOT EDIT.
// Source of truth: the annotated Go request structs in backend-core.
// Regenerate: cd backend-core && go run ./cmd/schemagen

import type { RpcSchema } from "../schemaForm/schemaTypes";

import balanceAllocateSchema from "./balance_allocate.schema.json";
import balancingRuleSetSchema from "./balancing_rule_set.schema.json";
import blindLevelAddSchema from "./blind_level_add.schema.json";
import clubCreateSchema from "./club_create.schema.json";
import clubMemberRoleSchema from "./club_member_role.schema.json";
import clubOwnerAddSchema from "./club_owner_add.schema.json";
import prizePoolAddSchema from "./prize_pool_add.schema.json";
import rakeConfigSetSchema from "./rake_config_set.schema.json";
import tableCreateSchema from "./table_create.schema.json";
import tournamentCreateSchema from "./tournament_create.schema.json";

export const RPC_SCHEMAS: Record<string, RpcSchema> = {
  "balance_allocate": balanceAllocateSchema as unknown as RpcSchema,
  "balancing_rule_set": balancingRuleSetSchema as unknown as RpcSchema,
  "blind_level_add": blindLevelAddSchema as unknown as RpcSchema,
  "club_create": clubCreateSchema as unknown as RpcSchema,
  "club_member_role": clubMemberRoleSchema as unknown as RpcSchema,
  "club_owner_add": clubOwnerAddSchema as unknown as RpcSchema,
  "prize_pool_add": prizePoolAddSchema as unknown as RpcSchema,
  "rake_config_set": rakeConfigSetSchema as unknown as RpcSchema,
  "table_create": tableCreateSchema as unknown as RpcSchema,
  "tournament_create": tournamentCreateSchema as unknown as RpcSchema,
};

export function getRpcSchema(rpc: string): RpcSchema | undefined {
  return RPC_SCHEMAS[rpc];
}
